# modified version of https://github.com/immich-app/immich/blob/main/.github/workflows/docker.yml

name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      with:
        driver-opts: |
          image=moby/buildkit:v0.10.6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: ${{ !github.event.pull_request.head.repo.fork }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate docker image tags
      id: metadata
      uses: docker/metadata-action@v5
      with:
        flavor: |
          # Disable latest tag
          latest=false
        images: |
          name=ghcr.io/${{ github.repository }}
        tags: |
          # Tag with branch name
          type=ref,event=branch
          # Tag with pr-number
          type=ref,event=pr
          # Tag with git tag on release
          type=ref,event=tag
          type=raw,value=release,enable=${{ github.event_name == 'release' }}

    - name: Determine build cache output
      id: cache-target
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          # Essentially just ignore the cache output (PR can't write to registry cache)
          echo "cache-to=type=local,dest=/tmp/discard,ignore-error=true" >> $GITHUB_OUTPUT
        else
          echo "cache-to=type=registry,mode=max,ref=ghcr.io/${{ github.repository }}-build-cache:mono-firefly-sync" >> $GITHUB_OUTPUT
        fi

    - name: Build and push image
      uses: docker/build-push-action@v5.0.0
      with:
        file: Containerfile
        target: runtime
        platforms: "linux/amd64"
        # Skip pushing when PR from a fork
        push: ${{ !github.event.pull_request.head.repo.fork }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-build-cache:mono-firefly-sync
        cache-to: ${{ steps.cache-target.outputs.cache-to }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
